group: travis_latest
language: python
cache: pip
matrix:
  include:
    - python: 3.7
      dist: xenial    # required for Python 3.7 (travis-ci/travis-ci#9069)
      sudo: required  # required for Python 3.7 (travis-ci/travis-ci#9069)
    # power support  
    - python: 3.7
      arch: ppc64le
      dist: xenial    # required for Python 3.7 (travis-ci/travis-ci#9069)
      sudo: required  # required for Python 3.7 (travis-ci/travis-ci#9069)
      
install:
  - python setup.py install
  - pip install flake8
before_script:
  # stop the build if there are Python syntax errors or undefined names
  - flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics
  # exit-zero treats all errors as warnings.  The GitHub editor is 127 chars wide
  - flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics --quiet
script:
  # Help message.
  - wafw00f --help
  # Testing for no WAF case
  - wafw00f https://google.com
  # Testing for Cloudflare
  - wafw00f https://yoxall.me.uk
  # Testing for ModSecurity
  - wafw00f http://celebritytweets.co.za

notifications:
  on_success: change
  on_failure: change  # `always` will be the setting once code changes slow down
